### ISSUE TITLE
Number of active users in a district

### ISSUE THREAD

**Issue by arjunk** [avniproject/lfeteach#11]
## Context 
Monitoring & Evaluation team needs to verify whether observers are genuinely recording observations. Looking at the average score card will help them verify this

Reference Sheet https://docs.google.com/spreadsheets/d/1ddSJQDQkIAS9EO2rq3spAH7SnE087EWdFHavPCmcRUA/edit#gid=835283860

## Acceptance Criteria

- [x] Report developed in Metabase in collection https://reporting.lfe.avniproject.org/collection/2-data
- [x] Aggregate and Linelist with tables as per the specified format
- [x] Filters as mentioned in the sheet
- [x] Aggregate should take to line list of observation to see details of observations
- [ ] Clicking on link from line list should take user to DEA to view actual observation

**Comment by sachsk** [comment]
Report link: https://reporting.lfe.avniproject.org/question/18-total-number-of-active-users-in-a-district

**Comment by utkarshavni** [comment]
@sachsk  @arjunk can we close this?
