### ISSUE TITLE
[LFE] App changes 2.0

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/lfeteach#23]
**_Changes will be done LFE Teach org on Aani server_**

Requirement sheet for referenece -
https://docs.google.com/spreadsheets/d/1ePv6aLKIu8Y47kc773dTpeO6sb8QIAjzXL_kvugY57s/edit#gid=0

- [x]  **Add a splash screen**
Logo here : https://github.com/avniproject/avni-client/blob/lfe/packages/openchs-android/android/app/src/main/assets/icons/teachap-logo.png

- [x] **Observation Encounter** 
   Time on Task:
- Timer at 4m, 9m and 13m for the snapshot
(Same as done on Staging LFE org)

- [x] **Offline Home dashboard** - create card for  Total Draft Observations/ Unsaved observations

- [x] Add videos-
 https://drive.google.com/drive/folders/1hbVEIfJIchixafhTBCKRhdnMgIQ0iDhG

- [x] Add missing fields in the **Teacher registration** -
Teacher CMSF ID
Phone Number

- [x] **Observation encounter** - Aupopulate Segment 2 Basic details from Segment 1's basic details. User should be able to edit.

- [x] Feedback Menu Item should take to this Google form https://docs.google.com/forms/d/1sDR1nlHPIiuq4GKWHvjEDrSgSt2ghfPtu0YSd2ZXp7A/edit?ts=6305ff52

**Comment by AchalaBelokar** [comment]
- [] - N/A is not getting auto selected when its the only option
