### ISSUE TITLE
[LFE] Misc tasks post Go Live

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/lfeteach#39]
Create duplicate dashboards for AP Teach org

- [x] Primary Observations (Summary Dashboard) [AP Teach] - **Nupoor**

- [x] Primary Observations (Detailed Dashboard) [AP Teach] - **Nupoor**,  **Beulah**,  **Taqi**

- [x]  Secondary Observations (Summary Dashboard) [AP Teach]  - **Beulah**

- [x] Secondary Observations (Detailed Dashboard) [AP Teach]  - **Taqi**

- [x] Classroom Observations Trackers (State Level) [AP Teach] - **Taqi**

- [x] Classroom Observations Trackers (District Level) [AP Teach] - **Beulah**

- [x] Create district_geojson table in AP Teach  

set role teachap;
create table district_geojson
(
    id        serial
        primary key,
    dist_name text  not null,
    geojson   jsonb not null
);

- [x] Create script to add details , details are under https://drive.google.com/file/d/1lyTTwHvmULupXq0iMD9LQx1785hrQtIX/view?usp=share_link

**Comment by nupoorkhandelwal** [comment]
set role teachap;
create table user_details
(
    id                      serial
        primary key,
    name                    text,
    avni_username           text
        references users (username),
    primary_status          boolean,
    secondary_status        boolean,
    mobile_number           bigint,
    new_district_name       text,
    mandal_name             text,
    is_voided               boolean default false
);

select *
from users;

insert into user_details( name, avni_username, primary_status, secondary_status, mobile_number,
                          new_district_name, mandal_name,
                         is_voided)
select name,
       username,
       '',
       '',
       phone_number,
       "District",
       "Mandal",
       disabled_in_cognito
from users
         left join catchment_address_mapping vcamt on catchment_id = vcamt.catchment_id
         left join teachap.address on address.id = vcamt.addresslevel_id;

**Comment by Gojo-Taqi** [comment]
List of charts with geo_json dataset :-

**Comment by AchalaBelokar** [comment]
- [ ]  Primary Observations (Detailed Dashboard) not showing the observation in percentage
![Screenshot 2023-02-20 at 7.34.15 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/7c69deaf-de66-41ba-bf93-aafecc1c65b6)  form

**Comment by AchalaBelokar** [comment]
- [ ] Secondary Observations (Summary Dashboard)  sequence is missing.
![Screenshot 2023-02-20 at 11.10.17 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/fddfe3d2-0caf-45b6-9828-c7ad5e95b0cb)
