### ISSUE TITLE
[AP Teach] Report for user wise details

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/lfeteach#41]
- [ ] On AP Teach, create a report with following details

Filters  - District
               Mandal
               Complex
               School

Report - 

![Screenshot 2023-02-15 at 4.52.11 PM.png](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/0bda00dd-66e3-47b9-a66e-3dda6746d930)

**Comment by utkarshavni** [comment]
@vedfordev @sachsk   This is an old card - if this is already done or not required, we can close it.
