### ISSUE TITLE
[LFE] Dashboard changes

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/lfeteach#45]
Make changes in the LFE reports (Superset) as mentioned in the referred sheet. 

Refer this sheet for changes:
https://docs.google.com/spreadsheets/d/1D1h6K89XBxfl9Pv03JTYBhu-OuaOf4z6CpsIif-2XtE/edit#gid=1776045527

**Comment by vedfordev** [comment]
Most of them resolved. For null value awaiting response.

**Comment by utkarshavni** [comment]
@vedfordev   @sachsk   do we have response on this? If yes, we can move the card.
