### ISSUE TITLE
[LFE] Update Pass/fail status 

### ISSUE THREAD

**Issue by sachsk** [avniproject/lfeteach#48]
- [x] We have created a table (user_status) with users pass fails status according to the status data in the superset should be shown.

- If the user is pass in primary, only primary observations should be counted in all reports.
- If the user is pass in secondary, only secondary observations should be counted in all reports.

**NOTE**
- While editing the query please remove the use of the ``catchment_address_mapping``  table.
- After making changes please test all charts once.

- [x] Dashboard information : Avni to provide information on the source of data for each widget as there are mismatches between the dashboard counts and raw counts as reflected in the longitudinal export on the console.

- [x] Teachers registered vs observed - Avni has changed the logic of the table on one dashboard. This logic should be reflecting on all the dashboards.

**Comment by vedfordev** [comment]
For Dashboard information use below sheet :

https://docs.google.com/spreadsheets/d/1v7WEZDujklDNuQE6LXgZjVs880NAKdmTacRqScLZKag/edit#gid=0

**Comment by nupoorkhandelwal** [comment]
- [ ] Primary Observations (Summary Dashboard) [AP Teach]

- [ ] Primary Observations (Detailed Dashboard) [AP Teach]

In this dashboard multiple cards have query which is looking for secondary status in case of primary teacher![Screenshot 2023-04-27 at 3.28.14 PM.png](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/5a0381af-188b-4275-a7ff-d556d1532152)s

**Comment by nupoorkhandelwal** [comment]
- [ ] Primary Observations (Detailed Dashboard) [AP Teach]
