### ISSUE TITLE
[LFE] Misc tasks for dashboard

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/lfeteach#51]
- [ ] Observations Total Mismatch - Total observations completed v/s total observations displayed when elements were downloaded

- [x] Removal/merging of user ids:
 A. Remove - 9495999683@teachap (Anjaly Gopi - LFE user)
 B. Merge observations of  N TARAKESWARA RAO - 9407570141@teachap in 9704570141@teachap
  C. B.J.P.JOSEPJ - He has 2 login ids - 8897557203@teachap and 9573793285@teachap. Please keep 9573793285@teachap and disable 8897557203@teachap. Migrate observations from disabled ID to the active id.
- [x] Cards to be added on the Primary and Secondary Summary Dashboards - Total observations and Total observers to be added
- [x]  Temporarily disable sync for the older version users - To avoid the dashboards from crashing
- [ ] Legends for behaviors and elements to be sorted.  For elements it has to be 1 to 5. For behaviors since L,M,H cannot be sorted right now can it be stored as 1.L   2.M and 3.H so that it is sorted numerically.
- [x]  0 Observation done by users widget not reflecting correct counts
- [x] Observations data - Data is required in the long format. Alter the existing widget in the App Sync Dashboard so that LFE can download and verify data in long format which is currently being exported in wide 
- [x] Eliminating null value in primary and secondary dashboard in summary and 
       detail dashboard

- [x] upload user_status data from following 
https://docs.google.com/spreadsheets/d/1qc5KUzIklrRNrJslJ2vt34OZP3f_v1GSdrdRKjlOw4E/edit#gid=1809296564
- [x] Update status in tracker sheet here once they are worked upon and tested.
https://docs.google.com/spreadsheets/d/1D1h6K89XBxfl9Pv03JTYBhu-OuaOf4z6CpsIif-2XtE/edit#gid=1776045527

**Comment by vedfordev** [comment]
Observations Total Mismatch - Total observations completed v/s total observations displayed when elements were downloaded

in this task we can do if we find any qa issue

**Comment by vedfordev** [comment]
qa require for

- [ ] Eliminating null value in primary and secondary dashboard in summary and
detail dashboard (check for pie chart)

- [ ] Cards to be added on the Primary and Secondary Summary Dashboards - Total observations and Total observers to be added
(check total observers and observation card reflecting as per condition)
