### ISSUE TITLE
[AP TEACH] Adding new questions at the end of observation sheet and Misc changes

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/lfeteach#53]
Reference ticket:
https://avni.freshdesk.com/a/tickets/2780
Reference sheet by LFE:
https://docs.google.com/spreadsheets/d/1CCuUjJpkU_ynGj9R2Enp6Q4-kgUESx0Z_c0GM-PC9QM/edit#gid=0

- [x] In Basic details - if Type of school is primary, value "6" is hidden. It should be shown if type of school is primary, and hide if Type of school is Secondary.
- [x] In Observations, Basic details section - change Grade question title to "Grade being taught"
- [x] In Observation, Basic details section -  change Subject question title to "Subject being taught"
- [x] Add a section "Fill in these details after the classroom observation" at the end of the Observations form.
- [x] Move Medium of Instruction question from Basic details section to the new section added above.
- [x] Change the title from "Medium of Instruction" to "Which language was used as a medium of instruction most of the time by the teacher during the class?"
- [x] Add question no. 2 to 7 after the Medium of instruction question. Refer the sheet
https://docs.google.com/spreadsheets/d/1AXecjQ6CsyoLVp8AZjRF15e14Dk61IhDvXBJrCOk-YM/edit#gid=0
UAT feedback sheet received from client for reference 
below is the attached list of action items to be done before moving to production as per client feedback during UAT.

https://docs.google.com/spreadsheets/d/13H2UO1TqZdOvXzazGVF65cxlI7SCd2SYVBJFUVGOqUI/edit#gid=0

- [x] Question number is to be added as per point number 4 in the UAT feedback sheet.
- [x] auto selected option of "Interactive flat panel" should not remain selected when page appears to the observer. please refer point number 4 in the above UAT feeb back sheet.

**Comment by utkarshavni** [comment]
Moving this to QA failed - last two questions as mentioned in the reference sheet should only display the options which were selected in the previous question's answer.

**Comment by BEULAHEVANJALIN** [comment]
Added the same in segment 2

**Comment by Dinesh2019** [comment]
According to the requirement sheet, the 6 and 7 point is not reflected as per the requirement https://docs.google.com/spreadsheets/d/13H2UO1TqZdOvXzazGVF65cxlI7SCd2SYVBJFUVGOqUI/edit#gid=0

- [ ] If the primary is selected we shouldnt display the Q3 (students are actively particapating)
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/ae323a05-050c-4fa0-ae02-55384b04858c)

- [ ] we have to chnage the below question to "Please note down answers for the following questions"
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/7d1e68ef-c95f-47fa-8dec-ba791a2db9c4)
