### ISSUE TITLE
UAT feedback for timer questions

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/lfeteach#56]
- [x] timer has to be changed from 30 sec to 20 sec
- [x] display first all instruction for the time and learning questions after that ask for answer and make it mandatory to asnwer all questions.

**Comment by vedfordev** [comment]
Estimate: 1 hours

**Comment by vedfordev** [comment]
time taken : 1hour

**Comment by salilsamanvay** [comment]
Client is facing some issue, checked on 17th July 2023: 

- [ ] question 0.3 is reflecting for primary at the time when observer starts filling the response, it should behave same as the reminder is displayed currently. 
- [ ] Score options (1 - 5) are not getting changed basis response (H/ M/ L) of questions in the section. it was changing previously. please check the logic and implement the same.
- [ ] for timer right now 14 min 20 sec logic is implemented (4 min + 20 sec reminder+ 4 min 40 sec + 20 sec reminder + 4 min 40 sec + 20 sec reminder), we just need to add 40 sec more in the last to make a segment total duration of 15 mins as it teach tool time guideline, and after 15 mins only question should be displayed for answer to the observer. no edit for reminder positioning, for the last 40 sec only timer will be displayed.

- Client is facing slow response while selecting the option for answers, she wanted us to check if app is slow or her mobile is having some issue. currently she is facing at times 5 sec of delay in touching the screen and option getting selected. 

1. option to explore: time selection method for observation start time is in 24 hours right now, do we have capability to make it 12 hour and then ask for AM / PM

**Comment by vedfordev** [comment]
for 3rd point we can add reminder text and we put start time as 880 and stay time 20 sec.
If you ( @salilsamanvay ) want to do this please provide text you want to show.  
cc : @sachsk
