### ISSUE TITLE
changes to go live on urgent basis (4th Aug email requirements)

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/lfeteach#60]
[https://app.zenhub.com/files/504383768/5b98c482-f45a-4e6e-a748-6f494ada647f/download](https://app.zenhub.com/files/504383768/5b98c482-f45a-4e6e-a748-6f494ada647f/download)

- [ ] have to check data migration impact before new observation activity starts
- [x] for primary section in Basic details FEG add Social studies as an answer to subject question
- [x] FAQs are not shown up. Earlier, the information used to pop up when a question mark is clicked
    - Documentation is present but not linked so link the document to the respective FEG/FE.

Note for reference of point we discussed with client and internally: response for question no. 1.4 for both the segment is getting auto populated basis the response the user has entered for 1.4a and 1.4b the combination of 1.4a and 1.4b has different scenario, so same response for both the previous question is provided then it is showing correct response with single option as pre selected, but when response are different for last 2 questions and it is being edited then this is not de-selecting previously selected option, we are showing other options as well so that user can change it but client want it not to remain selected.
   - this is behaving as per product(asking for prod change)
- [ ] @sachsk to check if deselecting option is possible in this scenario.
- [x] at observation- Enter Data level: 
1.  Scheduled Time to be labelled as "Scheduled Time Per the Timetable"
2.  Actual Time to be labelled as "Time When Class Started"
- [x] Draft Encounters card title change : The draft encounters to be revised as "Draft Observations"
- [x] Change in question text under additional 7 question added in the end FEG "Fill in these details after the classroom observation":
1.  question no. 5 : change it with " 5. Please Select the different types of ICT that are present in the classroom"
2. Question no. 6 change it with "6. Select which of the above ICT is in working condition"

**Comment by vedfordev** [comment]
### Developer's Note : 

@sachsk @salilsamanvay we find out that ap teach has not mapping of documentation. So we take reference from lfeteachuat and doing changes accordingly.

**Comment by vedfordev** [comment]
**Script writing logic:**

1. check documentation id and form element id  in both org with uuid.
2. if count matches then proceed with further
3. take documentation uuid and form element id from org and write query to update

[Link of Query](https://gist.github.com/vedfordev/cad61509fcc20e51231d3cb7c3cd6c61)

@sachsk please verify query once
