### ISSUE TITLE
Move grade 6 back to Secondary

### ISSUE THREAD

**Issue by BEULAHEVANJALIN** [avniproject/lfeteach#61]
#### The goal is to undo the changes made in card #54.

**Steps to follow:**
- [x] Review previously written scripts and rewrite them to accommodate necessary changes in across form fields.
- [x] Make changes in the app designer as well
- [x] Verify that the skip logics for primary and secondary are working as expected

**Expectation:**
The primary level should show the grades from 1 to 5
And the secondary level should show 6 to 10 grades

**Additional information:**
Prod org: AP Teach
UAT org: apt uat

**Comment by BEULAHEVANJALIN** [comment]
[UAT bundle (before changes)](https://app.zenhub.com/files/504383768/cc3eac2d-ae28-437f-8fa2-0d6fc20a78c2/download)

**Comment by BEULAHEVANJALIN** [comment]
Scripts to update existing observations: https://gist.github.com/BEULAHEVANJALIN/08b06b5b7718640fedafbd7d2d36ee41

**Comment by BEULAHEVANJALIN** [comment]
Changes made to the following questions:
- Grade being taught
- Segment 1 - Snapshot 1:Time on Learning -> 0.1 Teacher provides learning activity to most students
- Segment 1 - Snapshot 2:Time on Learning -> 0.3 Students are actively participating in learning tasks
- Segment 1 - Classroom Culture - Supportive Learning Environment -> 1.4 The teacher does not exhibit bias and challenges stereotypes in the classroom
- Segment 2 - Basic details -> Segment 2 - Grade being taught

**Comment by Dinesh2019** [comment]
Test Scenarios:

1. Create the individual for secondary using 6 and validate the data is db is updated as expected and also in the client is displayed as per the requirement
2. Create the individual for primary and validate the data
3. Edit the data from primary to secondary 
4. Validate the old data as being updated to the secondary if it is as grade as 6
5. Verify if we have the old as 5 and 6 and check for the type of school


Issue: Skip logic is not working as excepted 
Steps to reproduce :
1. go to the segment page 
2. we have the question named 0.1 Teacher provides the learning activity to most students as yes or no if we select yes the below question option is displayed and no is will be updated as NA 
3. select yes and for the below question click any option and deselect it will display as an error
4. select no the option is selected N/A but the error still exists 
Excepted result: Error should not be displayed and proceed further 
Actual result: Error is displayed and not moved further

https://images.zenhubusercontent.com/504383768/752cea79-4374-446c-98e1-5e8507e8a76b/96c6d792_4dab_401f_8bb2_d216851e8e18.mp4

**Comment by Dinesh2019** [comment]
Created the bug card for this above issue and closing the card 
https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/lfeteach/62
