### ISSUE TITLE
Teachers updated profile CSV Uploads

### ISSUE THREAD

**Issue by arjunk** [avniproject/lfeteach#63]
Teachers are individuals which are observed by Observers (Users)

Please refer type of changes in the below mentioned excel sheet link
https://docs.google.com/spreadsheets/d/1MoTwmc6mMrEUzqk-auJ2ae-xG3qJ6s4yr2KYQ7xjX9M/edit#gid=0

Type of changes and count of records to be modified:
- [x] Teachers to be merged with ax existing teacher ID	1363
previous observations are also to be merged when merging the duplicate teacher profiles.
- [x] Teachers to be voided temporarily	2275
these teacher records are not confirmed yet, they might have to be changed to active in future. 
- [x] Address Update	36809
here teachers have to be moved from 1 location to another location for which we will update address of the teacher, client's expectation was that the past observations done for the teacher should also move with teacher profile, it has been to be discussed as moving records with teacher profile will disturb school wise observations. we have advised to keep the previous records as they are. by this only data of transfer cases will be impacted which is logical as well which they should communicate during the training.
please add if any other issue could arise due to leaving the old observations as is or any better solution to migrate observation data with teacher.

in total 	40,447 changes are to be done in teacher's data base 

- [x] CSV received from LFE
- [x] CSV ready for upload
- [x] CSV uploaded to production

**Comment by arjunk** [comment]
CSV upload currently does not update subject migrations. So if the teacher's schools are changed this will not be reflected automatically in the observer's device. There is a product bug related to this which needs to be fixed. 
https://github.com/avniproject/avni-server/issues/592

**Comment by sachsk** [comment]
Tech note:
To merge teacher write SQL script and move all encounter from one teacher to another and void the mentioned teacher

**Comment by sachsk** [comment]
@vedfordev i have voided teachers

**Comment by vedfordev** [comment]
**For merging Task :**

Created sql script for task @sachsk 

Merge : [Link](https://gist.github.com/vedfordev/4fcaf282ae131aa9a0f6e54f2f9cbf84)
Void : [Link](https://gist.github.com/vedfordev/f17b630f0243278895268ca145b36b09)

**Comment by vedfordev** [comment]
**For upload task:**

**Error Data :** [Link](https://docs.google.com/spreadsheets/d/1MoTwmc6mMrEUzqk-auJ2ae-xG3qJ6s4yr2KYQ7xjX9M/edit#gid=2076857026)


### Analysis of error data:
Error shows Address mismatched. 
Checked school with following query
```
select school.id,school.title, complex.title, mandal.title, district.title
from address_level school
         join address_level complex on complex.id = school.parent_id
         join address_level mandal on mandal.id = complex.parent_id
         join address_level district on district.id = mandal.parent_id
where
    school.title in (<list_of_school>);
```
shows 0 record. So, Conclusion is address is wrong for that data.

**Comment by vedfordev** [comment]
**currently getting association error :** 

Error - Encounter{uuid='7f33c702-d9e7-42d3-a4a0-e01826fe9ed4'} is unable to find Individual{uuid='5d25ad1c-d662-426d-b90f-b755062f30a6'}

**Comment by vedfordev** [comment]
@salilsamanvay @sachsk inform client some records are not updated due to issue in address. I added error data in sheet.

**Comment by salilsamanvay** [comment]
@vedfordev can you please explain the problem, so that LFE team can get it corrected to get these cases updated as well.

**Comment by vedfordev** [comment]
@salilsamanvay in [Error Record](https://docs.google.com/spreadsheets/d/1MoTwmc6mMrEUzqk-auJ2ae-xG3qJ6s4yr2KYQ7xjX9M/edit#gid=2076857026) there is issue related to address means address not available.They have to check with system and make changes with address.
