### ISSUE TITLE
Observers CSV Upload - Aug2023

### ISSUE THREAD

**Issue by arjunk** [avniproject/lfeteach#64]
There are 2 types of Observer: HM observer and CRP observer
Please refer below excel sheet to find list of cases separated by type of change which are to be done by Observer type.
https://docs.google.com/spreadsheets/d/13GJos6Q0Ln2FJxKTZWJOUz2hrl9joBlZlBR4PlZjjJs/edit#gid=1323240943

Below changes are to be done which are mentioned in the above excel sheet:

- [x] Catchment change: these are transfer cases, where catchment has to be updated.

- [x] **User name change cases**: as user name previously was generated by mobile number which the observer had provided with the profile, now user have changed their mobile number, so they wanted to modify the user name with latest mobile number, for which we have requested client to get the mobile number updated as user name cannot be changed.
for this if we want to see if can trigger the user name and password msg on update profile as well which as of now only gets triggered at the time of first time registration.

- note: in this also there are two type of users 1 who have accessed avni with previous user name, which should remember their user name, the other category is who haven't accessed avni with previous user name, so they could have issue with remembering their old user name.

- [x] Observers who are to be Voided Temporarily: these are those observers which are yet to be confirmed, so they might have to be activated in future.

**Note**
  Before uploading CSV please read this doc: https://docs.google.com/document/d/15T7cKsNTimSG9W2bip1sBWhhz1fUB85mMec6gkHo2Q8/edit?usp=sharing

- [x] CSV provided by LFE
- [x] CSV ready for upload
- [x] CSV uploaded to production

**Comment by salilsamanvay** [comment]
@sachsk in the process document for csv upload, should we add about how to modify the previously registered observers and mark them as void if they are not working as observer anymore?

**Comment by sachsk** [comment]
- [ ] void users--- via SQL

**Comment by sachsk** [comment]
@vaijayanthisundaram I have disabled teachers
