### ISSUE TITLE
UAT feedback received from Anjaly on 14th Aug 2023

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/lfeteach#65]
- [x] 1. New Teacher Registration- This feature was disabled, but now it seems enabled. Pls, disable it until further notice.
- [x] 2. In the observation sheet, in the list of subjects "Hindi" seems to be written as "हिंदी". Pls write that in English itself like the rest of the subjects. 
- [x] 3. in the classroom observation question number 3 is not suppose to be shown if response of question no. 2 is no., can we change the question number basis response, currently if response of question no. 2 is no then it shows question number 4 which looks like error to the observer.
update on 3rd point change question number as per below details:
for question no. 1: no change
For question no. 2: no change
for Question no. 3: change the number to 2.1
For question no. 4: change the sequence to 3
For question no. 5: Change the sequence to 3.1
For question no. 6: change the sequence to 3.2
for question no. 7: change the sequence to 3.3

- [x] change 6.3 question in both segments with "6.3 The students ask open ended questions or perform thinking tasks"
- [ ] Telugu translation is not provided by Clients, will move ahead with auto generated translation for 6.3 question which we are changing as per above point.

**Comment by salilsamanvay** [comment]
@BEULAHEVANJALIN 2nd task is not done, Hindi is not reflecting as expected. please check it.

**Comment by vedfordev** [comment]
### Segment 1 - Instruction - Critical thinking:

**Before :** 6.3 Students perform thinking tasks
**After :** 6.3 The students ask open ended questions or perform thinking tasks

### Segment 2 - Instruction - Critical thinking:

**Before :** 6.3 Students perform thinking tasks
**After :** 6.3 The students ask open ended questions or perform thinking tasks

**Comment by vedfordev** [comment]
@salilsamanvay @sachsk  as we check there are no telugu translation.

**Comment by Dinesh2019** [comment]
@salilsamanvay @vedfordev @sachsk 
In the segment under snapshot 3 for secondary we have the question named as 0.3 Students are actively participating in learning tasks which as auto populated read only value but we can able to see the question with option but it is not editable

Refer the video :
(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcElZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--737b71f3838882b21a41ddb5057ce7178443bcf4/device-2023-08-18-164719.webm)

**Comment by vedfordev** [comment]
@Dinesh2019 first issue fixed. second issue was related to fast sync try with different catchment.

**Comment by Dinesh2019** [comment]
1. Again the Hindi is showing in the Hindi language, not in English

(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXdqIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--93c41b77c971ca505ab80425773c3290e8b6f9e6/Screenshot%202023-08-22%20at%2011.30.56%20AM.png)

**Comment by vedfordev** [comment]
@Dinesh2019 sync again and test

**Comment by Dinesh2019** [comment]
Created the bug card in prod low-severity bug 

https://github.com/avniproject/avni-client/issues/1083
