### ISSUE TITLE
Go live for Observations Aug 2023

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/lfeteach#66]
UAT Org name : @APTUAT
Production org: @apteach

Move bundle from UAT to production:
below task are to be checked while moving the bundle:

- [x] Save a bundle of live app before making any change and paste the link of it in this card for future reference.

- [x] move UAT bundle to production

- [x] Check documentation linking is correctly mapped and working. if not check [Script](https://gist.github.com/vedfordev/cad61509fcc20e51231d3cb7c3cd6c61)
- [x] perform sanity testing on live app
- [x] Check translation for Hindi and permission
- [x] Execute Script as per prod [Card Reference](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/lfeteach/61) || [Script](https://gist.github.com/BEULAHEVANJALIN/08b06b5b7718640fedafbd7d2d36ee41)

Note: Need to discuss with vinay whether server update is required before this activity or not?

**Comment by vedfordev** [comment]
[AP Teach.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEVYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d5a8d3ca35f7177bd3a356b1c71fc2fc645560ef/AP%20Teach.zip)
[apt uat.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaElYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ef1a0c2b9531418efede56829754c962c5f972ab/apt%20uat.zip)

**Comment by vedfordev** [comment]
bundle as per 24 aug:

[AP Teach.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUF6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--956b1b4f23e305854da612183f55305e67fb0482/AP%20Teach.zip)
[apt uat.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUl6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8b3fded4af00412ae126a255783d15ca572cf797/apt%20uat.zip)
