### ISSUE TITLE
[Teach NL] App changes

### ISSUE THREAD

**Issue by arjunk** [avniproject/lfeteach#69]
Reference Sheet : 
https://docs.google.com/spreadsheets/d/16wr_A3yXUVUrcZMsacQvJ0Uz3x9vXH_ZHQ81B9x3xLY/edit#gid=0

- [x] for now just add/ modify subject names as per above sheet

task to pick up after NL team test it:

- [x] Primary or secondary question should auto populate
- [x] Class under primary and secondary is to be done basis requirement sheet
- [x] validation on multi-class selection for class selection question should be added that combination a user should be allowed to select only either between class 1- class 8 OR  class 9- class 10
- [x] change rule according to type of school
- [x]  UAT feedback

Note: last task is to avoid rule failure for Primary/ Secondary question auto populated response.

**Comment by salilsamanvay** [comment]
@vedfordev card is updated with logic for multi class selection, you can pick up the card, if you are ready to pick up new card

**Comment by vedfordev** [comment]
worked till segment - 2 snapshot 2

**Comment by vedfordev** [comment]
## Developer's Note : 

#### Presupposition :
In most of segment, If we have two same question then one might be for primary and one for secondary.

#### Steps for changing rule in segment:
1. If rule shows condition then we change directly with rule.
2. If rule doesn't have summary then check grade matching and do change accordingly.

#### Dev Testing Scenario :
1. Creating encounter for Primary type and Secondary type and check in summary
**reference  individual :** test dinaugtwo

**Comment by Dinesh2019** [comment]
Test scenario and test cases can be reviewed in the below link
