### ISSUE TITLE
[Teach NL] UAT Feedback

### ISSUE THREAD

**Issue by arjunk** [avniproject/lfeteach#71]
Teach team has shared the feedback changes in the below excel sheet
https://docs.google.com/spreadsheets/d/1GLQf0BGXvS6BalYi04qZtUU34NsadQV04t3bh7o7SZA/edit#gid=0

there are 9 feedback items in the above sheet link.

- [x] Disable "New teacher registration"
- [x] Password not displayed when clicked on the show password button, to be tested, right now I am not facing this issue from my login.
- [x] Password displayed without clicking on the show password button, to be tested, right now I am not facing this issue from my login.
- [ ] "hide the question "Type of School", No need to display Primary or secondary to observer, but it should get captured in the observation record.
- [x] Remove the edit option for the submitted observation data. 
- [x] Geo coordinates were not displayed on the observation page. It is mandatory to capture coordinates for every observation. please enable it or check why it is not working if already enabled.
- [ ] Buttons are slow. Needs repeated try’s : check if we also face the same issue then raise performance issue to product team.
- [ ] In the Draft Observations page, the app displays the draft of an incomplete observation with two options at the bottom - "Do" and "Delete". It would make more sense to change the text from "Do" to "Resume".
- [ ] Once the app was installed "Allow permission" message pops up which mentioned only photos and media, but not camera and location. Allow permission requests should be asked immediately after install for all the " camera, location photos and media, in one single pop up.

**Comment by salilsamanvay** [comment]
@sachsk request you to please review it once and see if any additional clarification is required, as per me feedback is clear from client end and developer can do these changes from excel sheet only.

**Comment by sachsk** [comment]
Point 4 - we can’t hide and capture the value of the question in form and some questions depend on this questions answer so don't hide the question.

**Comment by vedfordev** [comment]
## Developer's Note:

1. disable permission in everyone and testing group.
2. tested working fine.
3. tested working fine.
4. not doable.
5. disable permission in everyone and testing group.
6. add/update tracklocation via query at end.
7. have to check with product team.
8. not doable. 
9. not doable.  


query :
```
set role teachnluat;


select id
from users where (settings ->> 'trackLocation' = 'false'
    or settings ->> 'trackLocation' isnull)  and username != 'admin' and is_org_admin = false and last_modified_by_id !=1;  -- 40


update users
set settings  = jsonb_set(
        COALESCE(settings, '{}'::jsonb),
        '{trackLocation}',
        'true'::jsonb
    ),
    last_modified_by_id     = (select id from users where username = 'vedantr@teachnluat'),
    last_modified_date_time = now()
where( settings ->> 'trackLocation' = 'false'
    or settings ->> 'trackLocation' isnull)   and username != 'admin' and is_org_admin = false and last_modified_by_id !=1;


select *
from users where id in (
10217,
10225,
10226,
10227,
10228,
10229,
10230,
10232,
10233,
10234,
10235,
10236,
10237,
10238,
10239,
10240,
10241,
10242,
10243,
10224,
10244,
10245,
10246,
10247,
10248,
10250,
10251,
10252,
10253,
10254,
10255,
10256,
10257,
10258,
10259,
10260,
10261,
10262,
10263,
10249

    );

```

**Comment by Dinesh2019** [comment]
When we do not turn on the location and proceed with the observation the GPS Cordinates are empty but soon after connecting to GPS the GPS coordinates are updated unless again come and click on the observation or after completing the form and clicking on next then we come back to the page the GPS Cordinates are updated

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0hvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--19d217465a7354f503510fc0b3ce79a6be0337a5/Screen%20Recording%202023-09-28%20at%206.58.37%20PM.mov

**Comment by Dinesh2019** [comment]
The app asks for permission when if the new user click on the observation 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1B0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--94f4dd05dd8fc21414133513c2d0d383f743b701/Screenshot%202023-09-29%20at%2010.26.43%20AM.png
