### ISSUE TITLE
Location update csv upload

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/lfeteach#74]
Below pasted excel sheet link has the list of locations which are to be modified (spelling change) and locations which are to be added in the location list on avni

https://docs.google.com/spreadsheets/d/1SX28cAfZK2h6c8EXM61djZYGA158fxqibzJokkEGNzU/edit#gid=0

- [x] Location spelling modification.
- [ ] new locations are to be added.

**Comment by sachsk** [comment]
Tech notes:
Update location name via SQL script.
Upload new location via CSV upload 
Estimate: 1hr

**Comment by Dinesh2019** [comment]
@sachin as discussed in the morning stand-up this card does not require the QA. So closing this card
