### ISSUE TITLE
Minor change (Teach AP)

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/lfeteach#76]
Below form link is to be updated on Teach AP Prod org under more section feedback form link. Please refer below excel sheet for screenshot of the location on the app where modifications are to be made

Excel sheet for reference: https://docs.google.com/spreadsheets/d/1P2g2HG4JsHK9blfQxqCM8iKhya_HtQdmh9FXNwinEzc/edit#gid=0

- [x] refer point no. 3 on the above excel link : New external link:  https://lfe.surveycto.com/collect/teachap_issueresolution?caseid=

**Comment by Gojo-Taqi** [comment]
Made the changes on both UAT and production and tested as well
