### ISSUE TITLE
Teach NL UAT feedback 4th Oct 2023

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/lfeteach#78]
on the below card 2 items are to be re-tested / re-analysed:

https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/lfeteach/71

- [x] Geo coordinates were not displayed on the observation page. It is mandatory to capture coordinates for every observation. Anjaly is facing issue to get GPS lat long populated with her login.

- [x] Question: Replace Type of School with " The Teach tool manual to be followed for this observation: "
In the Answer : replace "Primary"  with "Teach Primary" or Replace "Secondary" with "Teach Secondary"

PS: The answer should be auto-displayed based on the grade selected by the observer
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVlRQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ed194d4e0d95eaef76bc9e0a3aedb5b5eae155e/LFE%20Teach%20NL%20primary-%20secondary%20image.jpeg)

**Comment by salilsamanvay** [comment]
@Dinesh2019 you can test the location coordinate issue faced by Anjaly, I assume that you have her login details to test this, do let me know if you need any support on this.

**Comment by Dinesh2019** [comment]
@salilsamanvay I have a username but need to get the password yesterday I asked for the password she told me the issue is fixed for the feedback form. If possible can you help me to get it?

**Comment by Dinesh2019** [comment]
Yes @salilsamanvay looks good to me I think she might turn off the track location in the app but I am not sure 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFFLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ce2a64a0551826723f1550874948817d2cbb23e/Screen%20Recording%202023-10-05%20at%206.14.44%E2%80%AFPM.mov

**Comment by salilsamanvay** [comment]
@sachsk fyi..

**Comment by Dinesh2019** [comment]
@nupoorkhandelwal @salilsamanvay since we have prod issue for this point Question: Replace Type of School with " The Teach tool manual to be followed for this observation: "
In the Answer : replace "Primary" with "Teach Primary" or Replace "Secondary" with "Teach Secondary" as discussed in skype channel 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3NZQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e336e6fb29930d4560ca1f941f170008f6d185b/Screen%20Recording%202023-10-09%20at%206.08.02%E2%80%AFPM.mov

**Comment by nupoorkhandelwal** [comment]
Currently, translation is not showing up when ship answers rule is applied on it , created product bug card for the same -
https://github.com/avniproject/avni-client/issues/1128

**Comment by Dinesh2019** [comment]
The issue is fixed 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFpSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57de0dac643c62570117b3fe118e06157e3df599/Screenshot%202023-10-19%20at%202.56.20%E2%80%AFPM.png
