### ISSUE TITLE
CSV upload issues

### ISSUE THREAD

**Issue by sachsk** [avniproject/lfeteach#80]
- [x] Void teacher with 0 observations.
- [x] HM username update [Sheet link](https://docs.google.com/spreadsheets/d/13GJos6Q0Ln2FJxKTZWJOUz2hrl9joBlZlBR4PlZjjJs/edit#gid=781560430&range=A2)
    - [x]  Disable & void the old users and create a new user with an updated username and mobile number
- [x] CRP username update [Sheet link](https://docs.google.com/spreadsheets/d/13GJos6Q0Ln2FJxKTZWJOUz2hrl9joBlZlBR4PlZjjJs/edit#gid=1509852874&range=A2)
    - [x]  Disable & void the old users and create a new user with an updated username and mobile number

- [x] Teacher upload [Sheet link](https://docs.google.com/spreadsheets/d/1pvlzRR4wBe6rql5Wd8FML1hOYRfTbkkN5B5zYHS6BLY/edit#gid=0)
- [x]  Disable user 
- [x]  Teacher address update (upload teacher which was not uploaded because of address error now we have fixed address issue) [Sheet link](https://docs.google.com/spreadsheets/d/1MoTwmc6mMrEUzqk-auJ2ae-xG3qJ6s4yr2KYQ7xjX9M/edit#gid=2076857026&range=A2)
- [x] HM catchment mismatched issue [Link](https://docs.google.com/spreadsheets/d/1ruwTZ_COsaVy8FvWzOo7LOGdRo2-2atDqKLQMbKa6IE/edit#gid=541775141&range=A114) 
    - Current catchment address is not matching with the new updated address for 16 HM
 - [x] CRP Catchment mapping issue
     - Current catchment address is not matching with the new updated address

**Comment by vedfordev** [comment]
For voiding teacher 

query :
```
set role teachap;

-- total ind
select count(*)
from individual;
-- 185997

-- teacher with observation
select count(distinct individual.id)
from individual
join encounter e on individual.id = e.individual_id;
-- 39092


-- teacher with 0 observation
with enc as(
    select distinct individual_id
    from encounter
)
select count(individual.id)
from individual
where id not in (select * from enc
);
-- 146905

-- teacher with 0 observation
select count(distinct individual.id)
from individual
left join encounter e on individual.id = e.individual_id
where e isnull
;
-- 146905


with enc as(
    select distinct individual_id
    from encounter
)
update individual
set last_modified_date_time = current_timestamp + ( (id * 11) * interval '1 millisecond'),
    manual_update_history = 'voiding individual 0 observation',
    is_voided = true
where id not in (select *
                 from enc
);


```

**Comment by sachsk** [comment]
@vedfordev 
we have upgraded the server you can start to upload teacher, upload in the batches of 10k only

**Comment by vinayvenu** [comment]
@sachsk @salilsamanvay 
1. Server has been downgraded from t3.xlarge to t3.medium
2. Temporary database changes rolled back. Details of exact commands here - https://github.com/avniproject/lfeteach/blob/main/Migrations/Temporarily%20Modify%20title_lineage_locations_view.sql

**Comment by sachsk** [comment]
HM catchment issue: for some schools same school is present in the database with a different address hierarchy.
