### ISSUE TITLE
[Teach NL] App updates

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/lfeteach#81]
## Context (Why)
In Nagaland, the duration of one period for primary grades is just 30 minutes. Which is not sufficient for an entire observation with 2 segments to be done. To resolve this issue, the World Bank has given us approval to do an observation with only one segment. 

An additional option should be given to the user to skip segment 2 and proceed with the preview page and finally save and sync the observation. **This feature should be made available for the primary grade observations only.** The data that will be captured in the dashboard should not be affected because of the skipped segment. 

## Acceptance Criteria (What)
Org name :  **Teach NL UAT**
- [x] On the last form element group of Segment 1, introduce a new question -
"Do you want to skip the Segment-2 ?" (Yes/No) (Mandatory) (Logic - Should show up only if the Type of School is selected as "Primary")

- [x] In case the answer to new question "Do you want to skip the Segment-2 ?" is "Yes" then all the **Primary questions of Segment 2** should be skipped. 

## Tech approach (How)
We can do this by adding skip logic rule to Form Element group along with null check.

**Comment by salilsamanvay** [comment]
@nupoorkhandelwal for the LFE NL average scorecard, there are 3 scenarios:

1. When users select the class that comes under Secondary then the user will fill in both segments:
no change in current solution: The same logic that is currently in use is ok i.e. average score of both the segment
2. When users select the class that comes under Primary and only fills both segments: 
No change in current solution: The same logic that is currently in use is ok i.e. average score of both the segment
3. When users select the class that comes under Primary and only fills 1 segment only:
change required for this segment : 
a. calculate basis only 1 segment score.
or
b. consider the same score of segment 1 for segment 2 to maintain symmetry.

**Comment by nupoorkhandelwal** [comment]
@vedfordev just pass the value of Segment 1 as it is when the value of Segment 2 is absent.

**Comment by vedfordev** [comment]
@nupoorkhandelwal @Dinesh2019 as currently we are unable to create location and catchment in lfe. we are doing dashboard test later.

**Comment by Dinesh2019** [comment]
Test scenario :

1. Register the teacher and start the observation as primary using the skip logic yes excepted it should skip segment 2 and point to the date of observation's actual result as excepted in skipped segment 2
2. Register the teacher and start the observation as primary  using the skip logic No excepted it should not skip the segment 2 actual as excepted it displayed the segment 2 form 
3. Register the teacher and start the observation as secondary the skip logic question should not display and proceed to the segment 2 form 
4. Edit the observation when the skip logic question is given as No and edit to yes except then segment2 details need to be removed and saved.
5.  Edit the observation when the skip logic question is given as yes and edit to No except then the segment2 details form should be displayed and the user needs to fill the form

**Comment by Dinesh2019** [comment]
@nupoorkhandelwal @vedfordev We found a bug when we applied the skip logic the segment 2 class size alone is displayed in the summary 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjQwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2524c74abf8f5aaf3b56da5177cd91c2b67855e/Screenshot%202023-10-13%20at%209.30.08%E2%80%AFPM.png

**Comment by vedfordev** [comment]
@sachsk @nupoorkhandelwal @Dinesh2019 For me it is working fine. Tried but unable to reproduce. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG80QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ef0d765dbf6c8636e7a5045ef7627ecba494c2f/Screenshot%202023-10-16%20at%2012.05.39%20PM.png)

**Comment by Dinesh2019** [comment]
@sachsk  Can you check if this is in the edit scenario
