### ISSUE TITLE
Feedback from LFE team via email from Anjaly on 16th Oct

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/lfeteach#82]
Below changes are requested by LFE team:
**Organisation : Teach nagaland**
- [x] On the teacher registration page remove CFMS ID question, as there is no CFMS ID in Nagaland.
- [x] On the observation encounter page we ask user to provide a date to schedule the next observation, here same text is shown twice once as a page header, and then same text is shown for the question as well. to avoid confusion and make it more clearer for the users it is proposed to change the header language from "Date of next Observation" to Schedule next observation"
screen shot of page where change has to be made is pasted below for point number 2.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEpCQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a3a800d464b7378c8efad1dfabd064a4618325f/image.png)

**Comment by Gojo-Taqi** [comment]
@sachsk is it "Teach nagaland" or "Teach NL UAT"?

**Comment by salilsamanvay** [comment]
@Gojo-Taqi please first do it on UAT, after testing we will move it to prod

**Comment by salilsamanvay** [comment]
Yes, I have updated the card with CFMS ID.
