### ISSUE TITLE
[Teach NL]Segment 2 Skip logic for Secondary

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/lfeteach#86]
**Context**: earlier LFE team knowledge was that Primary class has 30 mins duration of each class period, and secondary has 45 mins duration, while doing the training LFE team learned that apart from Primary and secondary Nagaland has a third category of school type that is middle schools where both primary as well as secondary has class duration as 30 mins only. so it has been decided to provide skip options on segment 2  for secondary classes as well.

**Acceptance criteria:** 
we already have added skip logic for segment 2 when a class between 1st to 6th is selected which comes under school type as Primary, now we have to add skip options for secondary school type as well which has 7th to 9th Class.

**Tech approach:** 
 we have added a question at the end of segment 1 "do you want to skip segment 2" (added the zenhub card details below) in that we have provided a skip option if the type of school is Primary, by removing that skip logic we will give a skip option for both the school types (Primary as well as secondary)

**Zenhub card for reference:**
https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/lfeteach/81

**Note**

Test the dashboard card once and check the test cases mentioned on this [Card](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/lfeteach/81)

DO this changes on uat first

**Comment by BEULAHEVANJALIN** [comment]
Tech task: To remove skip logics that are added as part of #81
