### ISSUE TITLE
[Teach AP] Demo Video link to be updated

### ISSUE THREAD

**Issue by sachsk** [avniproject/lfeteach#87]
Context: LFE teach has developed demo videos for users on how to use Avni app to enter the observations points. we need to update old videos with latest video provided by LFE team.

Acceptance criteria: 

- [x] the client is asking to change the name of "videos" which reflects as an options to access online demo videos under more menu.
Renaming "Video" to "Demo Videos of the app"

- [x] latest videos have to be updated on "Demo videos of the app" option when users click on it.
"Demo videos of the app" to reach this place from home page click on more section there you will be able to find this option.

Tech approach: Via custom menu this video folder has to be updated.

latest video folder link provided by LFE for AP teach: https://drive.google.com/drive/folders/1ADOA3ega2LMWD4lpg8hsgxl6zviqHpar

UAT org: apt uat
Prod org: AP Teach

Note: The same activity of renaming the button is done for teach NL as well, please refer below card for more clarity.
https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/lfeteach/77

**Comment by Dinesh2019** [comment]
@Gojo-Taqi @salilsamanvay changes look good in the UAT we have to move the change to prod

test execution video:
https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnhZQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d32f2434eb32484a2e53de0a4fbe2129a8a1395e/Screen%20Recording%202023-10-20%20at%202.50.22%E2%80%AFPM.mov
