### ISSUE TITLE
Teach NL Draft observation feature is required

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/lfeteach#88]
## Context:
 Draft observation feature, LFE AP teach has a feature where the observer can save the in-progress observation as a draft and continue to fill it later. the same feature is also supposed to be enabled for LFE Teach NL. This has come as feedback from the client after going live. Please review why it wasn't added earlier as the requirement was to copy AP teach with agreed changes.

## Acceptance criteria: 
The user should be able to see the observation as a draft observation if they started an observation and hasn't completed it.
- It won't show up if you directly go to the Dashboard, but if you come back to it later, the draft will show up. 
-  If this is a planned encounter, it won't show up as a draft but will show the form as filled when you go to it. 

## Tech Approach:
 You can just enable the draft feature from the org setting.

**Comment by sachsk** [comment]
@salilsamanvay we have raised a support ticket for this as this is prod bug.
https://avni.freshdesk.com/a/tickets/3169
