### ISSUE TITLE
Superset dashboard issues

### ISSUE THREAD

**Issue by sachsk** [avniproject/lfeteach#91]
- [x] In Classroom Observations Trackers (State Level) dashboard Mandal filter not getting apply to Userwise Observation Count chart
- [x] Charts are breaking on applying the daterange filter in below dashboard
     -  Primary Observations (Detailed Dashboard)
     -  Secondary Observations (Detailed Dashboard)
     -  Primary Observations (Summary Dashboard)
     -  Secondary Observations (Summary Dashboard)

**Comment by vedfordev** [comment]
## Notes :

### For Mandal Filter
checked in query and find out mandal spelling was not according to filter. So changed it.

### Daterange filter 
checked after applying filter and find out that there are too many time column. So removed is temopral for columns apart from encounter_dat_time
