### ISSUE TITLE
Recreate the superset dashboards

### ISSUE THREAD

**Issue by sachsk** [avniproject/lfeteach#93]
## Context 
By mistake anjaly deleted 4 dashboard and there is no way to restore db as its using local db.
we have decided to create new dashboard with existing charts. in the document we you can find which charts are present in the dashboard.

Link for doc file: https://docs.google.com/document/d/1XUCjyXJVmmeUNu_HO8hfVmYwaQ20KiECrlL-sPhysVs/edit#heading=h.5eudw53o5pq

Dashboards 
- [x] Classroom Observations Trackers (State Level) [NL Teach]
- [x] Classroom Observations Trackers (District Level) [NL Teach]
- [x] Primary Observations (Summary Dashboard) [Teach NL]
- [x] Primary Observations (Detailed Dashboard) [Teach NL] 
- [x] User access has to be update with new dashboard links

**Comment by adamsanadi6** [comment]
Started working on "Classroom Observations Trackers (State Level) [NL Teach]"
Following charts are done :
1. Observations Complete
2. Active Observes
3. Blocks Observed
4. Schools Observed
5. Userwise Observation Count

**Comment by adamsanadi6** [comment]
Links
1. Classroom Observations Trackers (State Level) [NL Teach]: http://52.66.206.164/superset/dashboard/70

**Comment by BEULAHEVANJALIN** [comment]
User Access to be updated

**Comment by vedfordev** [comment]
check first this card

**Comment by vedfordev** [comment]
check first this card

**Comment by vedfordev** [comment]
check first this card
