### ISSUE TITLE
[Teach AP] Upload user status for observers

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/lfeteach#96]
## Support ticket 
 https://avni.freshdesk.com/a/tickets/3327

## Task 
Around 300 users have missing primary/secondary status in the table - user_status. We need to upload the this status shared by client - https://docs.google.com/spreadsheets/d/1ogdlaHrdLb-4_zOdFT8Iqnm-zrGI8wMwR1x0gCtctoI/edit#gid=0

This status is being used in reports, and since the users don't have this status, client is facing number mismatch issues on Superset dashboard

## Context -
To have more context on user_status table , check this doc -
https://docs.google.com/document/d/15T7cKsNTimSG9W2bip1sBWhhz1fUB85mMec6gkHo2Q8/edit

**Comment by vedfordev** [comment]
## Notes:

1. formated document as per public table. (ref: Missing Status - Avni use)
2. imported file in user_status table
3. checking query for data
```
select *
from user_status where id > 6625;
--shows count 288
```
