### ISSUE TITLE
[Teach AP Support] Migrate data for a duplicate teacher

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/lfeteach#97]
## Support Ticket 
https://avni.freshdesk.com/a/tickets/3513

## Context
There are duplicate subjects "Kumbha Krishna Kumari", we need to move encounters from one of the subject to the other subject. 

## Tech tasks

- [x] Write a script to update the individual id of the encounters for anyone of the subject to the other subject with name "Kumbha Krishna Kumari"
- [x] Post migration void the individual which has no encounters associated with it

**Comment by Gojo-Taqi** [comment]
Created a product support card for review - https://avni.freshdesk.com/a/tickets/3555

**Comment by Gojo-Taqi** [comment]
Link to the script - https://github.com/avniproject/data-fixes/blob/main/lfe/Teachap%20data%20fix.sql
